### ISSUE TITLE
Runtime errors when running project locally.

### ISSUE THREAD

**Issue by nputnam** [spotify/bigtable-autoscaler#45]
I was trying to run this project locally and encountering an exception. Digging in a bit it seems the pom is using a newer version of Guava that is supported by all the dependent libraries. Modifying the pom to use Guava 20. Fixed the issue locally and also produces a clean build. 

`            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>20.0</version>
            </dependency>`

Full exception for reference. 

`15:14:05.625 [pool-1-thread-1] ERROR [::] com.spotify.autoscaler.Autoscaler - Unexpected Exception!
java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: com.google.common.util.concurrent.Futures.transform(Lcom/google/common/util/concurrent/ListenableFuture;Lcom/google/common/base/Function;)Lcom/google/common/util/concurrent/ListenableFuture;
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncRun.run$$$capture(CompletableFuture.java:1629)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: com.google.common.util.concurrent.Futures.transform(Lcom/google/common/util/concurrent/ListenableFuture;Lcom/google/common/base/Function;)Lcom/google/common/util/concurrent/ListenableFuture;
	at com.google.api.core.ApiFutures.transform(ApiFutures.java:99)
	at com.google.api.gax.paging.AbstractPage.createPageAsync(AbstractPage.java:66)
	at com.google.cloud.monitoring.v3.PagedResponseWrappers$ListTimeSeriesPage.createPageAsync(PagedResponseWrappers.java:428)
	at com.google.cloud.monitoring.v3.PagedResponseWrappers$ListTimeSeriesPagedResponse.createAsync(PagedResponseWrappers.java:387)
	at com.google.cloud.monitoring.v3.MetricServiceSettings$6.getFuturePagedResponse(MetricServiceSettings.java:463)
	at com.google.cloud.monitoring.v3.MetricServiceSettings$6.getFuturePagedResponse(MetricServiceSettings.java:454)
	at com.google.api.gax.rpc.PagedCallable.futureCall(PagedCallable.java:63)
	at com.google.api.gax.rpc.UnaryCallable$1.futureCall(UnaryCallable.java:126)
	at com.google.api.gax.rpc.UnaryCallable.futureCall(UnaryCallable.java:87)
	at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
	at com.google.cloud.monitoring.v3.MetricServiceClient.listTimeSeries(MetricServiceClient.java:778)
	at com.google.cloud.monitoring.v3.MetricServiceClient.listTimeSeries(MetricServiceClient.java:747)
	at com.spotify.autoscaler.client.StackdriverClient.getCpuLoad(StackdriverClient.java:69)
	at com.spotify.autoscaler.AutoscaleJob.getCurrentCpu(AutoscaleJob.java:188)
	at com.spotify.autoscaler.AutoscaleJob.cpuStrategy(AutoscaleJob.java:195)
	at com.spotify.autoscaler.AutoscaleJob.run(AutoscaleJob.java:372)
	at com.spotify.autoscaler.Autoscaler.runForCluster(Autoscaler.java:123)
	at com.spotify.autoscaler.Autoscaler.lambda$null$0(Autoscaler.java:104)
	at java.util.concurrent.CompletableFuture$AsyncRun.run$$$capture(CompletableFuture.java:1626)
	... 4 common frames omitted`

**Comment by borislopezaraoz** [comment]
Thanks @nputnam 
merged https://github.com/spotify/bigtable-autoscaler/pull/48
